language: objective-c
osx_image: xcode10.1
before_install:
  - export LANG=en_US.UTF-8
  - bundle install
  - pod install
script: xcodebuild -workspace IGHTMLQuery.xcworkspace -scheme IGHTMLQuery -sdk iphonesimulator test -destination 'platform=iOS Simulator,name=iPhone 6 Plus' | xcpretty -c; exit ${PIPESTATUS[0]}
